name: Docker Push to ACR

on:
  workflow_call:
    inputs:
      image-name:
        description: 'The image name to push'
        required: true
        type: string
      acr-login-server:
        description: 'Azure Container Registry login server'
        required: true
        type: string
      tag:
        description: 'Image tag'
        required: true
        type: string
      ResourceGroup:
        description: 'Azure Resource Group name'
        required: true
        type: string
      acr-name:
        description: 'Azure Container Registry name'
        required: true
        type: string
      acr-location:
        description: 'Location of Azure Container Registry'
        required: true
        type: string
      app-name:
        description: 'Azure App Service name'
        required: true
        type: string
      runtime:
        description: 'Runtime Stack'
        required: true  
        type: string
        
    secrets:
      ACR_USERNAME:
        description: 'ACR_Username'
        required: true
      ACR_PASSWORD:
        description: 'ACR_Password'
        required: true
      AZURE_CREDENTIALS:
        description: 'AZURE_CREDENTIALS'
        required: true
      
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image-name }}-image
          path: ./docker_image
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      
      # Log in to Azure using GitHub Secrets
      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Create Resource Group
        run: |
          az group create --name ${{ inputs.ResourceGroup }} --location ${{ inputs.acr-location }}  
      
            
      # Create ACR 
      - name: Creating ACR
        run: |
          az acr create --resource-group ${{ inputs.ResourceGroup }} --name ${{ inputs.acr-name }} --sku Basic --location ${{ inputs.acr-location }}
      - name: Check if ACR exists
        run: |
          az acr show --name ${{ inputs.acr-name }} --resource-group ${{ inputs.ResourceGroup }} --output ACR.${{ inputs.acr-name }}.exists || echo "ACR does not exist"     
      # Log in to ACR
      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ inputs.acr-name }}
      
      # Verify if login was successful by listing repositories in ACR
      - name: List repositories in ACR
        run: |
          az acr repository list --name ${{ inputs.acr-name }} --output table
      
      # Load Docker image from artifact
      - name: Load Docker image from artifact
        run: |
          docker load -i ./docker_image/${{ inputs.image-name }}_${{ inputs.tag }}.tar    
            
      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker images
          docker tag ${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.acr-login-server }}/${{ inputs.image-name }}:${{ github.sha }}
          echo "Listing Docker images..."
          docker images
          docker push ${{ inputs.acr-login-server }}/${{ inputs.image-name }}:${{ github.sha }}