name: Docker Push to ACR

on:
  workflow_call:
    inputs:
      image-name:
        description: 'The image name to push'
        required: true
        type: string
      login-server:
        description: 'Azure Container Registry login server'
        required: true
        type: string
      tag:
        description: 'Image tag'
        required: true
        type: string
    
    secrets:
      username:
        description: 'ACR_Username'
        required: true
      password:
        description: 'ACR_Password'
        required: true
      AZURE_CREDENTIALS:
        description: 'AZURE_CREDENTIALS'
        required: true
      
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image-name }}-image
          path: ./docker_image
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      
      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_SERVER_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Load Docker image from artifact
        run: |
          docker load -i ./docker_image/${{ inputs.image-name }}_${{ inputs.tag }}.tar    
            
      - name: Push Docker image to ACR
        run: |
          docker images
          docker tag ${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.acr-login-server }}/${{ inputs.image-name }}:${{ github.sha }}
          echo "Listing Docker images..."
          docker images

          docker push ${{ inputs.acr-login-server }}/${{ inputs.image-name }}:${{ github.sha }}




